// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pazyn.EntityFrameworkCore.ExtendedProperties.Tests;

#nullable disable

namespace Pazyn.EntityFrameworkCore.ExtendedProperties.Tests.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250401205825_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pazyn.EntityFrameworkCore.ExtendedProperties.Tests.Entities.ExistingTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Auto incrementing id that is for internal use only");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AddAllAttributesToExistingField")
                        .HasColumnType("bit");

                    b.Property<string>("AddAttributeToExistingField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ExistingField_RenameExistingField")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Public unique identifier of this point transaction");

                    b.Property<bool>("RemoveAllAttributesFromExistingField")
                        .HasColumnType("bit");

                    b.Property<int>("RemoveFieldAndAttributeFromExistingField")
                        .HasColumnType("int");

                    b.Property<Guid>("RemovePiiAttributeFromExistingField")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ExistingTable", null, t =>
                        {
                            t.HasComment("Existing table for integration tests");
                        });
                });

            modelBuilder.Entity("Pazyn.EntityFrameworkCore.ExtendedProperties.Tests.Entities.TableToBeRemoved", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Auto incrementing id that is for internal use only");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllAttributesToBeRemoved")
                        .HasColumnType("int");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Public unique identifier of this point transaction");

                    b.Property<string>("PhiFieldToBeRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PiiFieldToBeRemoved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TableToBeRemoved", null, t =>
                        {
                            t.HasComment("Table to be removed for integration tests");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
